name: update, rebuild & deploy
on:
  schedule:
    - cron: '0 */6 * * *'
  repository_dispatch:

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  MONGODB_DB: ${{ secrets.MONGODB_DB }}
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
  TWITTER_API_ACCESS_TOKEN: ${{ secrets.TWITTER_API_ACCESS_TOKEN }}
  TWITTER_API_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_API_ACCESS_TOKEN_SECRET }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: prod
      - run: npm install
      - run: node cli/index.js update
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
